In [1]:
import pandas as pd

mat = pd.read_csv('/content/student-mat.csv', sep=';')
por = pd.read_csv('/content/student-por.csv', sep=';')

print(mat.shape)
print(por.shape)

(395, 33)
(649, 33)

In [2]:
mat['course_type'] = 'Math'
por['course_type'] = 'Portuguese'

df = pd.concat(
    [mat, por],
    ignore_index=True
)

print(df.shape)

(1044, 34)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 34 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   school       1044 non-null   object
 1   sex          1044 non-null   object
 2   age          1044 non-null   int64
 3   address      1044 non-null   object
 4   famsize      1044 non-null   object
 5   Pstatus      1044 non-null   object
 6   Medu         1044 non-null   int64
 7   Fedu         1044 non-null   int64
 8   Mjob         1044 non-null   object
 9   Fjob         1044 non-null   object
 10  reason       1044 non-null   object
 11  guardian     1044 non-null   object
 12  traveltime   1044 non-null   int64
 13  studytime    1044 non-null   int64
 14  failures     1044 non-null   int64
 15  schoolsup    1044 non-null   object
 16  famsup       1044 non-null   object
 17  paid         1044 non-null   object
 18  activities   1044 non-null   object
 19  nursery      1044 non-null   object
 20  higher       1044 non-null   object
 21  internet     1044 non-null   object
 22  romantic     1044 non-null   object
 23  famrel       1044 non-null   int64
 24  freetime     1044 non-null   int64
 25  goout        1044 non-null   int64
 26  Dalc         1044 non-null   int64
 27  Walc         1044 non-null   int64
 28  health       1044 non-null   int64
 29  absences     1044 non-null   int64
 30  G1           1044 non-null   int64
 31  G2           1044 non-null   int64
 32  G3           1044 non-null   int64
 33  course_type  1044 non-null   object
dtypes: int64(16), object(18)
memory usage: 277.4+ KB

In [4]:
df.isnull().sum()

school         0
sex            0
age            0
address        0
famsize        0
Pstatus        0
Medu           0
Fedu           0
Mjob           0
Fjob           0
reason         0
guardian       0
traveltime     0
studytime      0
failures       0
schoolsup      0
famsup         0
paid           0
activities     0
nursery        0
higher         0
internet       0
romantic       0
famrel         0
freetime       0
goout          0
Dalc           0
Walc           0
health         0
absences       0
G1             0
G2             0
G3             0
course_type    0
dtype: int64

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,course_type
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,Math
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,Math
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,Math
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,Math
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,Math

In [6]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3', 'course_type'],
      dtype='object')

In [7]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

encoders = {}

for col in df_encoded.select_dtypes(include='object').columns:
    le = LabelEncoder()

    df_encoded[col] = le.fit_transform(
        df_encoded[col]
    )

    encoders[col] = le

In [8]:
X = df_encoded.drop(
    columns=['G3']
)

y = df_encoded['G3']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

rf.fit(
    X_train,
    y_train
)

pred = rf.predict(X_test)

In [11]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print(
    "MAE:",
    mean_absolute_error(
        y_test,
        pred
    )
)

print(
    "RMSE:",
    mean_squared_error(
        y_test,
        pred
    ) ** 0.5
)

print(
    "R2:",
    r2_score(
        y_test,
        pred
    )
)

MAE: 0.9531259968102074
RMSE: 1.667294028655543
R2: 0.820199077359094

In [12]:
import joblib

joblib.dump(
    rf,
    'student_performance_rf.pkl'
)

['student_performance_rf.pkl']

In [13]:
feature_columns = X.columns.tolist()

joblib.dump(
    feature_columns,
    'student_performance_features.pkl'
)

['student_performance_features.pkl']

In [16]:
df.to_csv(
    'student_performance_final_dataset.csv',
    index=False
)

In [15]:
joblib.dump(
    encoders,
    'student_performance_encoders.pkl'
)

['student_performance_encoders.pkl']